
# jekyll configuration
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme 
name: Digi-Health
description: Helps to identify the problems
title: 
author:
markdown: kramdown
footer-links:
  email: 48dhinakar@gmail.com
  github: https://github.com/Dhinz123/health.github.io
url:
permalink: /:title/
